sender_mail: andras.csillag.tech@gmail.com
schedules:
  - team_name: Svábhegy FC
    division: Blsz II. 1.csoport
    url: https://adatbank.mlsz.hu/club/59/5/25606/2/249120.html
    attendees:
      - cs23andris@gmail.com
      - andras.csillag@datapao.com